[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "406ce6c"
hash = "f5afc904d5106ee368c8aa2ded43bd74"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-latte"
rev = "be0b21d"
hash = "273ee53369ccfbf7feb9b0c65e387ed8"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-frappe"
rev = "be0b21d"
hash = "ab7c71d442d3a9e16331ea0d95ab36a8"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-macchiato"
rev = "be0b21d"
hash = "5b1bf96d1cba26376087c37de993c517"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-mocha"
rev = "be0b21d"
hash = "ce320f877fe709b189433941aba747c4"
