[opener]
imv = [{ run = "imv %s", desc = "Open in imv", orphan = true }]

[[open.prepend_rules]]
mime = "folder/*"
use  = [ "imv", "edit", "open", "reveal" ]

# Use ouch to preview archives.
# https://github.com/ndtoan96/ouch.yazi#preview
[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run  = "ouch"
