---
.config/zellij/plugins/zellij-autolock.wasm:
  type: file
  url: https://github.com/fresh2dev/zellij-autolock/releases/download/0.2.2/zellij-autolock.wasm
  checksum:
    sha256: "69c95607bfd97e075d6762a44fdbc703a82a3c4909dbbbe43952f020487b8ea4"
