---
.config/zellij/plugins/vim-zellij-navigator.wasm:
  type: file
  url: https://github.com/hiasr/vim-zellij-navigator/releases/download/0.3.0/vim-zellij-navigator.wasm
  checksum:
    sha256: "77e5a2f62f7c1a698caf2574493d5d75587e0fd877cfba34c48caf731c24c58d"
