---
# Catppuccin

.local/share/theme/catppuccin/atuin:
  type: archive
  url: https://github.com/catppuccin/atuin/archive/abfab12de743aa73cf20ac3fa61e450c4d96380c.tar.gz
  exact: true
  stripComponents: 1
  include:
    - '*/themes/**'
  checksum:
    sha256: "566e6c20f62be92ee9817f395c50e33fc230724e014a00ee60858e881d8d4dd0"

.local/share/theme/catppuccin/eza:
  type: archive
  url: https://github.com/catppuccin/eza/archive/70f805f6cc27fa5b91750b75afb4296a0ec7fec9.tar.gz
  exact: true
  stripComponents: 1
  include:
    - '*/themes/**'
  checksum:
    sha256: "c8fe4bc862071a7aca025e56f95eb9e9f8e861f1d8934325e23ab11f8618aace"

.local/share/theme/catppuccin/gitui:
  type: archive
  url: https://github.com/catppuccin/gitui/archive/df2f59f847e047ff119a105afff49238311b2d36.tar.gz
  exact: true
  stripComponents: 1
  include:
    - '*/themes/**'
  checksum:
    sha256: "0e928438f3a967a5bc47aebcdf9899de1ce59ad4190cf291691364784361744d"

# cheat.sh

.local/bin/cht.sh:
  type: file
  executable: true
  url: https://cht.sh/:cht.sh
  checksum:
    sha256: "d3135e42b800ff2e7aac44d4dfe500f0f4e2c7eb00a1c2191b0dc8b28431f155"

# delta
.config/git/delta_themes:
  type: file
  url: https://raw.githubusercontent.com/dandavison/delta/acd758f7a08df6c2ac5542a2c5a4034c664a9ed8/themes.gitconfig
  checksum:
    sha256: "90f1b33b86f3517500786f36523464eb6d6e2f57da34e65f378c0d4dcd6878de"

# GitUI

.config/gitui/key_bindings.ron:
  type: file
  url: https://raw.githubusercontent.com/gitui-org/gitui/refs/heads/master/vim_style_key_config.ron
  checksum:
    sha256: "b982fd09208e953756dc4f3b23b1ac82f0c4c0e3c7a33d4b231a3c0c04435f56"

# Kitty

# UPSTREAM: The smart-splits.nvim python kittens must be placed in the kitty config root.
# https://github.com/mrjones2014/smart-splits.nvim/blob/e892a5da963813119d053af5b2260e3cd9d9f037/lua/smart-splits/mux/kitty.lua#L112
.config/kitty:
  type: archive
  url: https://github.com/mrjones2014/smart-splits.nvim/archive/refs/tags/v2.0.5.tar.gz
  exact: true
  stripComponents: 2
  include:
    - '*/kitty/*.py'
  checksum:
    sha256: "673f5ed4ff982a4176e3217a578bba641b226a068259f3b0b2d3fe0ecec29995"

# UPSTREAM: The kitty-scrollback.nvim loading.py file must be placed in the python directory under the kitty config root.
# https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/36d19dc85c0a1d0193e7c52d41129c4aa28b72e8/lua/kitty-scrollback/kitty_commands.lua#L273
.config/kitty/python:
  type: archive
  url: https://github.com/mikesmithgh/kitty-scrollback.nvim/archive/refs/tags/v6.3.0.tar.gz
  exact: true
  stripComponents: 2
  include:
    - '*/python/*.py'
  checksum:
    sha256: "7166083be39a80abe26bec5ca47f515ffc6b4fec36163ef8012485eaefa12bac"

# navi

.local/share/navi/cheats/denisidoro__cheats:
  type: git-repo
  url: https://github.com/denisidoro/cheats.git

# Zellij

.config/zellij/plugins/vim-zellij-navigator.wasm:
  type: file
  url: https://github.com/hiasr/vim-zellij-navigator/releases/download/0.3.0/vim-zellij-navigator.wasm
  checksum:
    sha256: "77e5a2f62f7c1a698caf2574493d5d75587e0fd877cfba34c48caf731c24c58d"
