---
.config/zellij/plugins/zellij-nvim-nav-plugin.wasm:
  type: file
  url: https://github.com/sharph/zellij-nvim-nav-plugin/releases/download/v1.0.0/zellij-nvim-nav-plugin.wasm
  checksum:
    sha256: "5b61c9b86af4b7a074f0d31fcf93be6e6e6598d7a47a5c95de3f64befdacc103"
