---
.config/atuin/themes:
  type: archive
  url: https://github.com/catppuccin/atuin/archive/abfab12de743aa73cf20ac3fa61e450c4d96380c.tar.gz
  exact: true
  stripComponents: 3
  include:
    - '*/themes/**'
  checksum:
    sha256: "566e6c20f62be92ee9817f395c50e33fc230724e014a00ee60858e881d8d4dd0"

.config/eza/themes:
  type: archive
  url: https://github.com/eza-community/eza-themes/archive/c03051f67e84110fbae91ab7cbc377b3460f035c.tar.gz
  exact: true
  stripComponents: 2
  include:
    - '*/themes/**'
  checksum:
    sha256: "68e401e09da34fd95d87f92078321222bf1302e047bf654deb36a5243c7f4c97"

.config/gitui/themes:
  type: archive
  url: https://github.com/catppuccin/gitui/archive/df2f59f847e047ff119a105afff49238311b2d36.tar.gz
  exact: true
  stripComponents: 2
  include:
    - '*/themes/**'
  checksum:
    sha256: "0e928438f3a967a5bc47aebcdf9899de1ce59ad4190cf291691364784361744d"

# UPSTREAM: The smart-splits.nvim python kittens must be placed in the kitty config root.
# https://github.com/mrjones2014/smart-splits.nvim/blob/e892a5da963813119d053af5b2260e3cd9d9f037/lua/smart-splits/mux/kitty.lua#L112
.config/kitty:
  type: archive
  url: https://github.com/mrjones2014/smart-splits.nvim/archive/refs/tags/v2.0.5.tar.gz
  exact: true
  stripComponents: 2
  include:
    - '*/kitty/*.py'
  checksum:
    sha256: "673f5ed4ff982a4176e3217a578bba641b226a068259f3b0b2d3fe0ecec29995"

# UPSTREAM: The kitty-scrollback.nvim loading.py file must be placed in the python directory under the kitty config root.
# https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/36d19dc85c0a1d0193e7c52d41129c4aa28b72e8/lua/kitty-scrollback/kitty_commands.lua#L273
.config/kitty/python:
  type: archive
  url: https://github.com/mikesmithgh/kitty-scrollback.nvim/archive/refs/tags/v6.3.0.tar.gz
  exact: true
  stripComponents: 2
  include:
    - '*/python/*.py'
  checksum:
    sha256: "7166083be39a80abe26bec5ca47f515ffc6b4fec36163ef8012485eaefa12bac"

.config/yazi/themes:
  type: archive
  url: https://github.com/catppuccin/yazi/archive/043ffae14e7f7fcc136636d5f2c617b5bc2f5e31.tar.gz
  exact: true
  stripComponents: 3
  include:
    - '*/themes/**'
  checksum:
    sha256: "92cbda4573e80784ab693fdf3b6c16636f2c1bb551f78935404eba8e8c911b40"

.config/zellij/plugins/vim-zellij-navigator.wasm:
  type: file
  url: https://github.com/hiasr/vim-zellij-navigator/releases/download/0.3.0/vim-zellij-navigator.wasm
  checksum:
    sha256: "77e5a2f62f7c1a698caf2574493d5d75587e0fd877cfba34c48caf731c24c58d"
