[".config/tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/refs/tags/v3.1.0.tar.gz"
  exact = true
  stripComponents = 1
  exclude = [
    "*/docs/**",
    "*/tests/**",
    "*/lib/**",
    "*/.*",
    "*/HOW_TO_PLUGIN.md"
  ]

  [".config/tmux/plugins/tpm".checksum]
    sha256 = "2411fc416c4475d297f61078d0a03afb3a1f5322fff26a13fdb4f20d7e975570"

[".config/tmux/plugins/tmux-sensible"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tmux-sensible/archive/refs/tags/v3.0.0.tar.gz"
  exact = true
  stripComponents = 1
  exclude = [
    "*.gitattribute"
  ]

  [".config/tmux/plugins/tmux-sensible".checksum]
    sha256 = "426dcf398d3073bb526db88921ff5734e5566a045b23c8194cb3646646f61c16"
