.TH dotfiles 7 2026-01-01 "razor-x"
.SH NAME
dotfiles \- personalized terminal and graphical user interface
.SH SYNOPSIS
This manual documents the environment, aliases, and tools
configured in razor-x/dotfiles.
.SH DESCRIPTION
TODO
.TE
.SS TOOLS
.TP
.BR bat (1)
A cat clone with syntax highlighting and Git integration.
.UR https://github.com/sharkdp/bat
.UE
.TP
.BR broot (1)
A new way to see and navigate directory trees.
.UR https://github.com/Canop/broot
.UE
.TP
.BR delta (1)
.SS ABBREVIATIONS
.TS
l l l l .
\fBAbbr\fR	\fBCommand\fR	\fBMnemonic\fR	\fBDescription\fR
_
a	rg	Ag	search
aa	batgrep	Ag	search with preview
z	zoxide	Zoom	directory jump
d	yazi	Directory	file manager
e	$VISUAL	Edit	open editor
l	eza	List	list files
x	ouch d	eXtract	decompress
v	bat -p	View	syntax highlight
vv	prettybat -p	View	formatted view
mx	zellij	MultipleX	terminal multiplexer
mon	zenith	Monitor	system monitor
.TE
